### ISSUE TITLE
Estimating # of spots in clusters

### ISSUE THREAD

**Issue by jstitlow** [fish-quant/big-fish#41]
Is there an integrated density method to estimate the # of spots in foci, similar to FQ in Matlab?

I see `nb_rna_in_foci = foci_coord[:, ndim].sum()` in the features.foci_features() function.  My understanding is that it works by counting up the number of spots in the foci ROI. Is that correct, and is that the only method available?

Sorry if I am overlooking something obvious. 
Thanks,
j

**Comment by muellerflorian** [comment]
Hey Josh,

you are right, we didn't add the equivalent of the integrated intensity method as we have it in Matlab. 

what we got so far is that we decompose dense RNA aggregates (could be transcription sites, or any other accumulation in the nucleus or cytoplasm). this step essentially attempts to estimate how many individual RNAs are within these dense regions. We then add another step where we call "foci" with method called [dbscan](https://en.wikipedia.org/wiki/DBSCAN). here, you need to specify how many RNA have to be within a pre-defined distance from each other, in order to be called a foci. 

an example is provided here: https://github.com/fish-quant/big-fish-examples/blob/master/notebooks/5%20-%20Detect%20spots.ipynb, in the section `Cluster decomposition`.


do you think the integrated intensity approach would make sense to be added?


best
F

**Comment by jstitlow** [comment]
**do you think the integrated intensity approach would make sense to be added?**
Not necessarily, do you think the new approach is comparable or even more accurate? Our concern is that the estimate of foci in the cluster will be underestimated if it relies on detection of individual foci.

**Comment by muellerflorian** [comment]
We didn't compare it to the integrated intensity. It is potentially more flexible since it allows to look at more "loose" clusters that spread out over a larger area. The integrated intensity really only works for very localized signals where RNAs are stacked on top of each other. 

concerning your concerns, not sure if I understand, maybe there is a mix-up and "foci" should actually be "RNA".

**Comment by jstitlow** [comment]
Thanks Florian. 
**"The integrated intensity really only works for very localized signals where RNAs are stacked on top of each other."**
Does the current approach work where RNAs are stacked on top of each other? 

For example, would you expect the algorithm to tell us that the cluster on the right has 8 spots, based on intensity?
![image](https://user-images.githubusercontent.com/5816582/108254683-55ae0d80-7129-11eb-9287-7f46a7fa6674.png)

**Comment by muellerflorian** [comment]
that's a nice graph :-)

it should (in principle). the conceptual idea of the decomposition and integrated intensity is similar. for **decomposition**, we use the mean image of individual RNAs, to then infer how many of those we need to deconstruct a cluster. for this, we actually iteratively "rebuild" the image of a cluster until this reconstructed image and the real image match best. 

**integrated intensity** is kind of shortcut, where we estimated the total signal of the cluster and then one of mean, individual RNA. the integrated intensity is based on the fit with a 3D Gaussian function. If your clusters are bigger and not regular in shape, this can quickly fail. 

**caveat 1**
one caveat with all of these estimations is that the intensities of individual RNAs can vary already quite a bit. in some papers, it was estimated that only about 60% of all oligos will bind for one given RNA, and this can vary. this can already give quite a bit of variability. 

**caveat 2**
A very important point is the definition of the individual RNA since this is the reference. If this is wrong, all the rest will not work too well either. we do this automatically based on somewhat ad-hoc criteria which work for us. but it's certainly better to also verify if this seems consistent. 

**caveat 3**
When clusters start to get very bright, then things can go quickly wrong. Essentially if the clusters get so intense that defocusing patterns that are as bright as individual RNAs appear. These defocusing patterns can then be mistaken for individual RNAs and the RNA counts per cluster are overcounted.

**Comment by jstitlow** [comment]
Excellent, thanks for the thorough explanation. I think the decomposition method suffices. 

Closing this issue, and editing the title to be less confusing.
