### ISSUE TITLE
v.0.6.1 thresholding type error

### ISSUE THREAD

**Issue by owigg** [fish-quant/big-fish#67]
Using big-fish 0.6.1 and running the following code from your example notebook

```
spots, threshold = detection.detect_spots(
    images=rna, 
    return_threshold=True, 
    voxel_size=(300, 103, 103),  # in nanometer (one value per dimension zyx)
    spot_radius=(300, 150, 150))  # in nanometer (one value per dimension zyx)
```
Generates the following error:

```
TypeError                                 Traceback (most recent call last)

File ~\anaconda3\envs\fish\lib\site-packages\bigfish\detection\spot_detection.py:516, in automated_threshold_setting(image, mask_local_max)
    514 # select threshold where the break of the distribution is located
    515 if count_spots.size > 0:
--> 516     optimal_threshold, _, _ = get_breaking_point(thresholds, count_spots)
    518 # case where no spots were detected
    519 else:
    520     optimal_threshold = None

File ~\anaconda3\envs\fish\lib\site-packages\bigfish\detection\utils.py:668, in get_breaking_point(x, y)
    645 """Select the x-axis value where a L-curve has a kink.
    646 
    647 Assuming a L-curve from A to B, the 'breaking_point' is the more distant
   (...)
    665 
    666 """
    667 # check parameters
--> 668 stack.check_array(x, ndim=1, dtype=[np.float64, np.int64])
    669 stack.check_array(y, ndim=1, dtype=[np.float64, np.int64])
    671 # select threshold where curve break

File ~\anaconda3\envs\fish\lib\site-packages\bigfish\stack\utils.py:135, in check_array(array, ndim, dtype, allow_nan)
    133 # check the dtype
    134 if dtype is not None:
--> 135     _check_dtype_array(array, dtype)
    137 # check the number of dimension
    138 if ndim is not None:

File ~\anaconda3\envs\fish\lib\site-packages\bigfish\stack\utils.py:172, in _check_dtype_array(array, dtype)
    169         break
    171 if error:
--> 172     raise TypeError("{0} is not supported yet. Use one of those dtypes "
    173                     "instead: {1}.".format(array.dtype, dtype))

TypeError: int32 is not supported yet. Use one of those dtypes instead: [<class 'numpy.float64'>, <class 'numpy.int64'>].

```
The error was suppressed by changing line 546 of spot_detection.py

from: `thresholds = np.array(thresholds)`
to: `thresholds = np.array(thresholds, dtype=np.int64)`

**Comment by Henley13** [comment]
Hi @owigg, do you use windows ? If yes, the error should be related to this [stackoverflow post](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine). By default your numpy arrays are in 32bit instead of 64bit. 

I will add a fix to solve this error whatever platform you use, thanks!

**Comment by owigg** [comment]
Thanks for the fix. Yes, I am using Windows 64 bit.

**Comment by Henley13** [comment]
Hi @luisub,

Since you work on windows, when you use numpy, arrays are defined in 32bit by default, instead of 64bit... 

See this [stackoverflow post](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine).

With some functions and intermediate functions, I am a bit too strict concerning the dtypes allowed, I will need to loose it for the next release (v0.6.2 I guess).

I will let this issue opened until I merge a PR solving it.

**Comment by luisub** [comment]
Hi, @Henley13 and @owigg. Thanks a lot for the feedback. I usually use Linux, and it has been working great! 

But we have undergrad students in the group who want to run codes on their personal Windows computers, and they are getting the error.

**Comment by muellerflorian** [comment]
Hello Arthur :-),  same problem here on a windows machine with version 0.6.1.

happy to test the new version once released.

**Comment by Henley13** [comment]
Hello, 

The new version (big-fish 0.6.2) should fix the error for window user. Tell me if some troubles persist.

Best,
Arthur
